# Generated by Django 2.2 on 2024-05-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profeilfeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfeilFeedItem',
            new_name='ProfileFeedItem',
        ),
    ]
